// Generated by CoffeeScript 1.6.3
(function() {
  var glossyParser, parseOssecSyslogAlert, stdin;

  glossyParser = require("glossy").Parse;

  stdin = process.openStdin();

  stdin.setEncoding('utf8');

  stdin.on('data', function(ossec_syslog_alert) {
    return parseOssecSyslogAlert(ossec_syslog_alert);
  });

  parseOssecSyslogAlert = function(ossec_syslog_alert) {
    var parsedObject;
    return parsedObject = glossyParser.parse(ossec_syslog_alert);
  };

}).call(this);

/*
//@ sourceMappingURL=.map
*/
