// Generated by CoffeeScript 1.6.3
(function() {
  var EventBuilder, GetMeta, OssecJsonAlertAttributesExtractor, ProcessOssecJsonAlert, UserExtractor, VariableExtractor;

  EventBuilder = require('./../event_builder');

  OssecJsonAlertAttributesExtractor = require('./../extractors/ossec_json_alert_attributes_extractor');

  VariableExtractor = require('./../extractors/variable_extractor');

  UserExtractor = require('./../extractors/user_extractor');

  GetMeta = require('./../extractors/get_meta');

  ProcessOssecJsonAlert = (function() {
    function ProcessOssecJsonAlert(ossecSyslogAlert) {
      this.ossecSyslogAlert = ossecSyslogAlert;
      if (debug) {
        console.log("Found OSSEC alert: " + this.ossecSyslogAlert);
      }
      this.event = new EventBuilder();
    }

    ProcessOssecJsonAlert.prototype.run = function() {
      this.extractJsonBlock();
      if (this.ossecAlert != null) {
        this.process();
        this.updateEvent();
        return this.event.event;
      } else {
        if (debug) {
          console.log("Log line does not contain an OSSEC alert?: " + this.ossecSyslogAlert);
        }
        return false;
      }
    };

    ProcessOssecJsonAlert.prototype.extractJsonBlock = function() {
      var match, ossecJsonPattern;
      ossecJsonPattern = /([A-Z][a-z]{2}\s\d{1,2}\s\d{2}:\d{2}:\d{2}).*ossec:\s({\s\"crit\"\:\s\d{1,2}\,\s\"id\"\:\s\d+.*\})/;
      match = this.ossecSyslogAlert.match(ossecJsonPattern);
      if (match) {
        this.timeStamp = match[1];
      }
      if (match) {
        return this.ossecAlert = JSON.parse(match[2]);
      }
    };

    ProcessOssecJsonAlert.prototype.process = function() {
      this.attributesExtractor = new OssecJsonAlertAttributesExtractor(this.logHeader, this.ossecAlert, this.event);
      this.attributes = this.attributesExtractor.run();
      this.variableExtractor = new VariableExtractor(this.ossecAlert, this.event);
      this.variables = this.variableExtractor.run();
      this.userExtractor = new UserExtractor(this.ossecAlert, this.event);
      return this.users = this.userExtractor.run();
    };

    ProcessOssecJsonAlert.prototype.updateEvent = function() {
      this.event.updateEvent({
        sourcePort: this.attributes.sourcePort
      });
      this.event.updateEvent({
        sourceIp: this.attributes.sourceIp
      });
      this.event.updateEvent({
        destinationIp: this.attributes.destinationIp
      });
      this.event.updateEvent({
        destinationPort: this.attributes.destinationPort
      });
      this.event.updateEvent({
        fileName: this.attributes.fileName
      });
      this.event.updateEvent({
        newMd5: this.attributes.newMd5
      });
      this.event.updateEvent({
        oldMd5: this.attributes.oldMd5
      });
      this.event.updateEvent({
        newSha1: this.attributes.newSha1
      });
      this.event.updateEvent({
        oldSha1: this.attributes.oldSha1
      });
      this.event.updateEvent({
        severity: this.attributes.severity
      });
      this.event.updateEvent({
        ruleId: this.attributes.ruleId
      });
      this.event.updateEvent({
        description: this.attributes.description
      });
      this.event.updateEvent({
        component: this.attributes.component
      });
      this.event.updateEvent({
        classification: this.attributes.classification
      });
      this.event.updateEvent({
        message: this.attributes.message
      });
      this.event.updateEvent({
        user: this.attributes.user
      });
      this.event.updateEvent({
        device: this.attributes.device
      });
      this.event.updateEvent({
        domains: this.variables.domains
      });
      this.event.updateEvent({
        emails: this.variables.emails
      });
      this.event.updateEvent({
        ipAddrs: this.variables.ipAddrs
      });
      this.event.updateEvent({
        users: this.users
      });
      return this.event.updateEvent({
        timestamp: this.timeStamp
      });
    };

    return ProcessOssecJsonAlert;

  })();

  module.exports = ProcessOssecJsonAlert;

}).call(this);

/*
//@ sourceMappingURL=process_ossec_json_alert.map
*/
