// Generated by CoffeeScript 1.6.3
(function() {
  var GetMeta, dns;

  dns = require('dns');

  GetMeta = (function() {
    function GetMeta() {}

    return GetMeta;

  })();

  module.exports = GetMeta;

}).call(this);
