// Generated by CoffeeScript 1.6.3
(function() {
  var VariableExtractor;

  VariableExtractor = (function() {
    function VariableExtractor(ossec_alert, event) {
      this.ossec_alert = ossec_alert;
      this.event = event;
      this.variables = {};
    }

    VariableExtractor.prototype.run = function() {
      if (debug) {
        console.log("Running Variable Extractor...");
      }
      this.extractDomains();
      this.extractEmails();
      this.extractIpAddrs();
      return this.variables;
    };

    VariableExtractor.prototype.extractIpAddrs = function() {
      var ipAddr, ipAddrPattern, match;
      ipAddrPattern = /(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/g;
      match = this.ossec_alert.message.match(ipAddrPattern);
      if (match) {
        this.ipAddrs = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = match.length; _i < _len; _i++) {
            ipAddr = match[_i];
            _results.push(ipAddr);
          }
          return _results;
        })();
      }
      this.variables["ipAddrs"] = this.ipAddrs;
      if (debug) {
        return console.log("IP Addrs: " + this.ipAddrs);
      }
    };

    VariableExtractor.prototype.extractDomains = function() {
      var domain, domainPattern, match;
      domainPattern = /([a-z0-9\-]+([\-\.]{1}[a-z0-9\-]+)*\.[a-z]{2,5})/ig;
      match = this.ossec_alert.message.match(domainPattern);
      if (match) {
        this.domains = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = match.length; _i < _len; _i++) {
            domain = match[_i];
            _results.push(domain);
          }
          return _results;
        })();
      }
      this.variables["domains"] = this.domains;
      if (debug) {
        return console.log("Domains: " + this.domains);
      }
    };

    VariableExtractor.prototype.extractEmails = function() {
      var email, emailPattern, match;
      emailPattern = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/ig;
      match = this.ossec_alert.message.match(emailPattern);
      if (match) {
        this.emails = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = match.length; _i < _len; _i++) {
            email = match[_i];
            _results.push(email);
          }
          return _results;
        })();
      }
      this.variables["emails"] = this.emails;
      if (debug) {
        return console.log("Emails: " + this.emails);
      }
    };

    return VariableExtractor;

  })();

  module.exports = VariableExtractor;

}).call(this);
