// Generated by CoffeeScript 1.6.3
(function() {
  var ClientSocket, OssecClient, ProcessOssecAlert, fs, io, optimist, root,
    __slice = [].slice;

  optimist = require('optimist');

  io = require('socket.io-client');

  fs = require('fs');

  ProcessOssecAlert = require('./process_ossec_alert');

  root = global;

  root.debug = true;

  OssecClient = (function() {
    function OssecClient() {}

    OssecClient.prototype.run = function() {
      var argv;
      this.io = new ClientSocket();
      optimist.usage('Uncommon Data OSSEC Adapter');
      optimist.options('f', {
        describe: 'Syslog file containing OSSEC JSON alerts',
        "default": process.argv.f
      });
      optimist.options('s', {
        describe: 'Read from STDIN (expecting Syslog file w/OSSEC JSON alerts)'
      });
      optimist.options('h', {
        describe: 'Show this message'
      });
      argv = optimist.argv;
      if (argv.f) {
        return this.readFromSyslogFile(argv.f);
      } else if (argv.s) {
        return this.readFromStdIn();
      } else {
        return console.log(optimist.help());
      }
    };

    OssecClient.prototype.readFromStdIn = function() {
      var stdin,
        _this = this;
      stdin = process.openStdin();
      stdin.setEncoding('utf8');
      return stdin.on('data', function(ossec_syslog_alert) {
        return _this.processLine(ossec_syslog_alert);
      });
    };

    OssecClient.prototype.readFromSyslogFile = function(filePath) {
      var last, stream,
        _this = this;
      stream = fs.createReadStream(filePath, 'utf8');
      last = "";
      return stream.on('data', function(chunk) {
        var lines, logLine, _i, _j, _len, _ref, _results;
        lines = (last + chunk).replace(/\\\|/g, '').split("\n");
        _ref = lines, lines = 2 <= _ref.length ? __slice.call(_ref, 0, _i = _ref.length - 1) : (_i = 0, []), last = _ref[_i++];
        _results = [];
        for (_j = 0, _len = lines.length; _j < _len; _j++) {
          logLine = lines[_j];
          _results.push(_this.processLine(logLine));
        }
        return _results;
      });
    };

    OssecClient.prototype.processLine = function(line) {
      var event;
      this.processAlert = new ProcessOssecAlert(line);
      event = this.processAlert.run();
      return this.io.emit(event);
    };

    return OssecClient;

  })();

  ClientSocket = (function() {
    function ClientSocket() {
      var config, url;
      if (debug) {
        console.log("Establishing socket.io connection... ");
      }
      config = {
        key: "",
        host: "localhost",
        port: 5000
      };
      url = "http://" + config.host + ":" + config.port;
      if (debug) {
        console.log(url);
      }
      this.socket = io.connect(url);
    }

    ClientSocket.prototype.emit = function(event) {
      console.log("emit...");
      if (debug) {
        console.log(event);
      }
      return this.socket.emit('message', [event]);
    };

    return ClientSocket;

  })();

  new OssecClient().run();

}).call(this);

/*
//@ sourceMappingURL=ossec_adapter.map
*/
